misconfigurations:
  - id: AVD-KSV-0014
    paths:
      - "*/charts/postgres*/**"
      - "*/charts/redis-ha*/**"
      - "*/charts/opentelemetry-collector*/**"
  - id: AVD-KSV-0118
    paths:
      - "*/charts/redis-ha*/**"
      - "*/charts/opentelemetry-collector*/**"
