toml-version = "v1.0.0"

[files]
include = ["**/*.toml"]

[format.rules]
line-width = 100

[[schemas]]
path = "tombi://www.schemastore.org/cargo.json"
include = ["**/Cargo.toml"]
format.rules.table-keys-order.enabled = false

[[overrides]]
files.include = ["**/Cargo.toml"]

[overrides.lint.rules]
tables-out-of-order = "off"
