[default]
extend-ignore-identifiers-re = []

[default.extend-words]
COSE = "COSE"

[files]
extend-exclude = [
    "demo",
    "supply-chain",
    "test_data/",
    "src/test_resources",
    "src/web/auth/mod.rs",
    "src/web/handlers/issue_credential.rs",
]