[default]
extend-ignore-identifiers-re = []

[default.extend-identifiers]

[default.extend-words]
Cose = "Cose"

[files]
extend-exclude = [
  "demo",
  "supply-chain",
  "src/test_resources",
  "src/web/auth/mod.rs",
  "src/web/handlers/issue_credential.rs"
]
