[default]
extend-ignore-identifiers-re = []

[default.extend-words]
Cose = "Cose"
flate = "flate"
Ue = "Ue"
Hashi = "Hashi"
AKS = "AKS"

[files]
extend-exclude = [
  "demo",
  "supply-chain",
  "test_data/",
  "src/test_resources",
]
