apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.metadata.name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.spec.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.spec.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.spec.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecret.spec.target.name }}
    creationPolicy: {{ .Values.externalSecret.spec.target.creationPolicy }}
  data:
  {{- range .Values.externalSecret.spec.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
  {{- end }}
