apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecret.spec.secretStoreRef.name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.aws.region }}
      auth:
        {{- if eq .Values.secretStore.aws.authType "jwt" }}
        jwt:
          serviceAccountRef:
            name: {{ .Values.secretStore.aws.serviceAccountName }}
        {{- else if eq .Values.secretStore.aws.authType "secret" }}
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.secretStore.aws.accessKeyIDSecretRef.name }}
            key: {{ .Values.secretStore.aws.accessKeyIDSecretRef.key }}
          secretAccessKeySecretRef:
            name: {{ .Values.secretStore.aws.secretAccessKeySecretRef.name }}
            key: {{ .Values.secretStore.aws.secretAccessKeySecretRef.key }}
        {{- end }}
