{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "status-list-server-chart.fullname" . }}-otel-collector-config
  labels:
    {{- include "status-list-server-chart.otelCollectorLabels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        timeout: 5s
        send_batch_size: 1024
    exporters:
      {{- if .Values.otelCollector.config.exporters.otlpEndpoint }}
      otlp/backend:
        endpoint: {{ .Values.otelCollector.config.exporters.otlpEndpoint | quote }}
        tls:
          insecure: {{ .Values.otelCollector.config.exporters.otlpTlsInsecure | default true }}
      {{- end }}
      debug:
        verbosity: basic
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [{{ if .Values.otelCollector.config.exporters.otlpEndpoint }}otlp/backend, {{ end }}debug]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
{{- end }}
