{{- if and (not .Values.externalSecret.enabled) .Values.statuslist.fallbackSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.statuslist.fallbackSecret.name | default "statuslist-secret" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
{{- range $key, $value := .Values.statuslist.fallbackSecret.stringData }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
