name: Conventional Commits

on:
  merge_group:
  workflow_dispatch:
  pull_request:
    types:
      - edited
      - opened
      - ready_for_review
      - reopened
      - synchronize

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Validate PR title
        if: ${{ github.event_name == 'pull_request' }}
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test

      - name: Validate commit messages
        uses: wagoid/commitlint-github-action@6cf16efdf4da5277c791d335142c03a0bdf1766e # v6.2.1
        with:
          configFile: commitlint.config.mjs
          helpURL: https://github.com/adorsys/status-list-server/blob/main/CONTRIBUTING.md#commit-messages
